hugoblox:
  schema: "2.0"

  identity:
    name: "Hadeel Saad"
    organization: ""
    type: person
    tagline: ""
    description: "Academic website for Hadeel Saad, Ph.D. candidate in paleontology at the University of Michigan."
    social:
      twitter: "GoOwnable"

  theme:
    mode: system
    colors:
      primary: "#DA77AC"
      secondary: "#F9B665"

  typography:
    pack: "academic"

  layout:
    radius: "md"
    spacing: "spacious"
    avatar_shape: square

  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    theme_picker: false
    language_switcher: true
    cta:
      enable: false
      text: ""
      url: ""
